version: "3.8"
services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "3000:3000"
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - REDIS_URL=redis://redis-db:6379
    depends_on:
      redis-db:
        condition: service_started

  redis-db:
    image: redis
