service: my-rubyshow
image: gambala/my-rubyshow
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
labels:
  traefik.http.routers.my-rubyshow-web.rule: Host(`ruby.show`, `www.ruby.show`, `new.ruby.show`)
  traefik.http.routers.my-rubyshow-web.middlewares: my-rubyshow-redirect-new,my-rubyshow-redirect-www,my-rubyshow-web-retry@docker
  traefik.http.middlewares.my-rubyshow-redirect-new.redirectregex.regex: "^http://new\\.ruby\\.show/(.*)"
  traefik.http.middlewares.my-rubyshow-redirect-new.redirectregex.replacement: "http://ruby.show/$1"
  traefik.http.middlewares.my-rubyshow-redirect-new.redirectregex.permanent: "true"
  traefik.http.middlewares.my-rubyshow-redirect-www.redirectregex.regex: "^http://www\\.ruby\\.show/(.*)"
  traefik.http.middlewares.my-rubyshow-redirect-www.redirectregex.replacement: "http://ruby.show/$1"
  traefik.http.middlewares.my-rubyshow-redirect-www.redirectregex.permanent: "true"
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
volumes:
  - my-rubyshow-storage:/rails/storage
env:
  secret:
    - RAILS_MASTER_KEY
    - SQLITE_DB
    - REDIS_HOST
    - REDIS_PORT
    - APP_DOMAIN
    - APP_HOST
    - GLITCHTIP_DSN
    - DEVISE_SECRET
    - GITHUB_KEY
    - GITHUB_SECRET
    - MAILGUN_API_KEY
    - RAILS_SERVE_STATIC_FILES
    - RECAPTCHA_SECRET_KEY
    - RECAPTCHA_SITE_KEY
    - SECRET_KEY_BASE
accessories:
  redis:
    image: redis:latest
    host: <%= ENV["REDIS_HOST"] %>
    port: <%= ENV["REDIS_PORT"] %>:6379
    directories:
      - data:/data
healthcheck:
  interval: 10s
builder:
  multiarch: false
