service: rubyshow
image: gambala/rubyshow
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
labels:
  traefik.http.routers.rubyshow-web.rule: Host(`ruby.show`, `www.ruby.show`, `new.ruby.show`)
  traefik.http.routers.rubyshow-web.middlewares: rubyshow-redirect-new,rubyshow-redirect-www,rubyshow-web-retry@docker
  traefik.http.middlewares.rubyshow-redirect-new.redirectregex.regex: "^http://new\\.ruby\\.show/(.*)"
  traefik.http.middlewares.rubyshow-redirect-new.redirectregex.replacement: "http://ruby.show/$1"
  traefik.http.middlewares.rubyshow-redirect-new.redirectregex.permanent: "true"
  traefik.http.middlewares.rubyshow-redirect-www.redirectregex.regex: "^http://www\\.ruby\\.show/(.*)"
  traefik.http.middlewares.rubyshow-redirect-www.redirectregex.replacement: "http://ruby.show/$1"
  traefik.http.middlewares.rubyshow-redirect-www.redirectregex.permanent: "true"
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - DB_HOST
    - DB_PORT
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - REDIS_HOST
    - REDIS_PORT
    - APP_DOMAIN
    - APP_HOST
    - BUGSNAG_API_KEY
    - DEVISE_SECRET
    - GITHUB_KEY
    - GITHUB_SECRET
    - MAILGUN_API_KEY
    - RAILS_SERVE_STATIC_FILES
    - RECAPTCHA_SECRET_KEY
    - RECAPTCHA_SITE_KEY
    - SECRET_KEY_BASE
accessories:
  db:
    image: postgres:15
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV["DB_PORT"] %>:5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    host: <%= ENV["REDIS_HOST"] %>
    port: <%= ENV["REDIS_PORT"] %>:6379
    directories:
      - data:/data
healthcheck:
  interval: 10s
builder:
  multiarch: false
