<% require "dotenv"; Dotenv.load(".env") %>

service: my-rubyshow
image: gambala/my-rubyshow
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: ruby.show
  app_port: 3000
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
volumes:
  - my-rubyshow-storage:/rails/storage
env:
  secret:
    - RAILS_MASTER_KEY
    - SQLITE_DB
    - REDIS_HOST
    - REDIS_PORT
    - APP_DOMAIN
    - APP_HOST
    - GLITCHTIP_DSN
    - DEVISE_SECRET
    - GITHUB_KEY
    - GITHUB_SECRET
    - MAILGUN_API_KEY
    - RAILS_SERVE_STATIC_FILES
    - RECAPTCHA_SECRET_KEY
    - RECAPTCHA_SITE_KEY
    - SECRET_KEY_BASE
accessories:
  redis:
    image: redis:latest
    host: <%= ENV["REDIS_HOST"] %>
    port: <%= ENV["REDIS_PORT"] %>:6379
    directories:
      - data:/data
builder:
  arch: arm64
