# frozen_string_literal: true

module Deploy
  def self.forbidden_locations
    %w(
      /88.php
      /cms/
      ^/.bzr
      ^/.git
      ^/.hg
      ^/.svn
      ^/_admin
      ^/aaa
      ^/adm/
      ^/admin/login.php
      ^/administrator
      ^/apple-app-site-association
      ^/away
      ^/backup
      ^/bitrix
      ^/browserconfig.xml
      ^/cache
      ^/cgi-sys
      ^/clientaccesspolicy
      ^/core/
      ^/data/
      ^/default.php
      ^/downloader
      ^/engine
      ^/go/
      ^/hostcmsfiles
      ^/html/logs.php
      ^/include/ajax
      ^/includes/init.php
      ^/index.php
      ^/installed
      ^/js/
      ^/license.php
      ^/m/
      ^/manager
      ^/media/system
      ^/mobile
      ^/modules/system
      ^/mysql
      ^/netcat
      ^/password_double_opt
      ^/phpmyadmin
      ^/redirect.php
      ^/scripts/init.js
      ^/sftp-settings
      ^/skin
      ^/sql
      ^/styles/skins
      ^/templates/system
      ^/typo3
      ^/uploads/goods
      ^/wp-admin
      ^/wp-login.php
      ^/xml/
      ^/xmlrpc.php
    ).freeze
  end
end
